// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, './.env') });

export default defineConfig({
  schema: path.join(__dirname, 'prisma/schema/'),
  datasource: {
    url: process.env.DATABASE_URL!,
  },
});
