services:
  mongo:
    image: mongo:latest
    container_name: ecommerce-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    command: mongod --replSet rs0 --bind_ip_all --auth --keyFile /etc/mongo-keyfile
    volumes:
      - /home/dhruva/mongo-keyfile:/etc/mongo-keyfile
