// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO account (account_id, provider, password, user_id)
VALUES ($1, $2, $3, $4)
`

type CreateAccountParams struct {
	AccountID string         `json:"account_id"`
	Provider  Provider       `json:"provider"`
	Password  sql.NullString `json:"password"`
	UserID    int64          `json:"user_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.AccountID,
		arg.Provider,
		arg.Password,
		arg.UserID,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_token (id, token, user_id, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	ID        string         `json:"id"`
	Token     string         `json:"token"`
	UserID    int64          `json:"user_id"`
	IpAddress sql.NullString `json:"ip_address"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const deleteRefreshTokensByID = `-- name: DeleteRefreshTokensByID :exec
DELETE FROM refresh_token WHERE id = $1
`

func (q *Queries) DeleteRefreshTokensByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensByID, id)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, token, user_id, revoked, ip_address, created_at, expires_at
FROM refresh_token
WHERE id = $1
`

type GetRefreshTokenRow struct {
	ID        string         `json:"id"`
	Token     string         `json:"token"`
	UserID    int64          `json:"user_id"`
	Revoked   bool           `json:"revoked"`
	IpAddress sql.NullString `json:"ip_address"`
	CreatedAt time.Time      `json:"created_at"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, id string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, id)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.Revoked,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateRefreshTokenRevoked = `-- name: UpdateRefreshTokenRevoked :exec
UPDATE refresh_token
SET revoked = $2, last_used = $3
WHERE id = $1
`

type UpdateRefreshTokenRevokedParams struct {
	ID       string       `json:"id"`
	Revoked  bool         `json:"revoked"`
	LastUsed sql.NullTime `json:"last_used"`
}

func (q *Queries) UpdateRefreshTokenRevoked(ctx context.Context, arg UpdateRefreshTokenRevokedParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenRevoked, arg.ID, arg.Revoked, arg.LastUsed)
	return err
}
