// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type DocumentType string

const (
	DocumentTypeGSTCERTIFICATE  DocumentType = "GST_CERTIFICATE"
	DocumentTypeBUSINESSLICENSE DocumentType = "BUSINESS_LICENSE"
	DocumentTypeIDENTITYPROOF   DocumentType = "IDENTITY_PROOF"
)

func (e *DocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentType(s)
	case string:
		*e = DocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentType: %T", src)
	}
	return nil
}

type NullDocumentType struct {
	DocumentType DocumentType `json:"document_type"`
	Valid        bool         `json:"valid"` // Valid is true if DocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentType), nil
}

type OrderStatus string

const (
	OrderStatusPENDING    OrderStatus = "PENDING"
	OrderStatusPROCESSING OrderStatus = "PROCESSING"
	OrderStatusSHIPPED    OrderStatus = "SHIPPED"
	OrderStatusDELIVERED  OrderStatus = "DELIVERED"
	OrderStatusCANCELLED  OrderStatus = "CANCELLED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentStatus string

const (
	PaymentStatusPENDING   PaymentStatus = "PENDING"
	PaymentStatusCOMPLETED PaymentStatus = "COMPLETED"
	PaymentStatusFAILED    PaymentStatus = "FAILED"
	PaymentStatusREFUNDED  PaymentStatus = "REFUNDED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type Provider string

const (
	ProviderGOOGLE      Provider = "GOOGLE"
	ProviderFACEBOOK    Provider = "FACEBOOK"
	ProviderGITHUB      Provider = "GITHUB"
	ProviderCREDENTIALS Provider = "CREDENTIALS"
)

func (e *Provider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Provider(s)
	case string:
		*e = Provider(s)
	default:
		return fmt.Errorf("unsupported scan type for Provider: %T", src)
	}
	return nil
}

type NullProvider struct {
	Provider Provider `json:"provider"`
	Valid    bool     `json:"valid"` // Valid is true if Provider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProvider) Scan(value interface{}) error {
	if value == nil {
		ns.Provider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Provider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Provider), nil
}

type Role string

const (
	RoleBUYER  Role = "BUYER"
	RoleSELLER Role = "SELLER"
	RoleADMIN  Role = "ADMIN"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type SellerStatus string

const (
	SellerStatusPENDING  SellerStatus = "PENDING"
	SellerStatusAPPROVED SellerStatus = "APPROVED"
	SellerStatusREJECTED SellerStatus = "REJECTED"
)

func (e *SellerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SellerStatus(s)
	case string:
		*e = SellerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SellerStatus: %T", src)
	}
	return nil
}

type NullSellerStatus struct {
	SellerStatus SellerStatus `json:"seller_status"`
	Valid        bool         `json:"valid"` // Valid is true if SellerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSellerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SellerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SellerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSellerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SellerStatus), nil
}

type Account struct {
	ID          int64          `json:"id"`
	AccountID   string         `json:"account_id"`
	Provider    Provider       `json:"provider"`
	IDToken     sql.NullString `json:"id_token"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Password    sql.NullString `json:"password"`
	PhoneNumber sql.NullString `json:"phone_number"`
	UserID      int64          `json:"user_id"`
}

type Address struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Pincode     int32     `json:"pincode"`
	Area        string    `json:"area"`
	City        string    `json:"city"`
	State       string    `json:"state"`
	Country     string    `json:"country"`
	PhoneNumber int64     `json:"phone_number"`
	UserID      int64     `json:"user_id"`
	LastUsed    time.Time `json:"last_used"`
}

type Admin struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Verified  bool      `json:"verified"`
	CreatedAt time.Time `json:"created_at"`
}

type Buyer struct {
	ID            int64                 `json:"id"`
	UserID        int64                 `json:"user_id"`
	LoyaltyPoints int32                 `json:"loyalty_points"`
	TotalOrders   int32                 `json:"total_orders"`
	Wishlist      pqtype.NullRawMessage `json:"wishlist"`
	CreatedAt     time.Time             `json:"created_at"`
}

type Cart struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	ProductID int64     `json:"product_id"`
	Selected  bool      `json:"selected"`
	Amount    int32     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type CheckoutInfo struct {
	ID     int64           `json:"id"`
	Data   json.RawMessage `json:"data"`
	UserID int64           `json:"user_id"`
}

type Order struct {
	ID            int64           `json:"id"`
	UserID        int64           `json:"user_id"`
	Address       json.RawMessage `json:"address"`
	SellerID      sql.NullInt64   `json:"seller_id"`
	AddressID     sql.NullInt64   `json:"address_id"`
	TotalAmount   float64         `json:"total_amount"`
	CreatedAt     time.Time       `json:"created_at"`
	Status        OrderStatus     `json:"status"`
	PaymentStatus PaymentStatus   `json:"payment_status"`
}

type OrderProduct struct {
	ID        int64         `json:"id"`
	ProductID int64         `json:"product_id"`
	SellerID  int64         `json:"seller_id"`
	Amount    int32         `json:"amount"`
	VariantID int64         `json:"variant_id"`
	OrderID   sql.NullInt64 `json:"order_id"`
}

type Payment struct {
	ID             int64          `json:"id"`
	OrderID        int64          `json:"order_id"`
	TransactionID  sql.NullString `json:"transaction_id"`
	PaymentGateway sql.NullString `json:"payment_gateway"`
	Amount         float64        `json:"amount"`
	Status         PaymentStatus  `json:"status"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Product struct {
	ID          int64         `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Price       float64       `json:"price"`
	ImageUrl    string        `json:"image_url"`
	IsActive    bool          `json:"is_active"`
	Discounted  sql.NullInt32 `json:"discounted"`
	SellerID    int64         `json:"seller_id"`
	CreatedAt   time.Time     `json:"created_at"`
	Category    string        `json:"category"`
}

type ProductVariant struct {
	ID          int64   `json:"id"`
	Size        string  `json:"size"`
	Description string  `json:"description"`
	Title       string  `json:"title"`
	Price       float64 `json:"price"`
	Stock       int32   `json:"stock"`
	ProductID   int64   `json:"product_id"`
}

type RefreshToken struct {
	ID        string         `json:"id"`
	Token     string         `json:"token"`
	UserID    int64          `json:"user_id"`
	Revoked   bool           `json:"revoked"`
	IpAddress sql.NullString `json:"ip_address"`
	LastUsed  sql.NullTime   `json:"last_used"`
	CreatedAt time.Time      `json:"created_at"`
	ExpiresAt time.Time      `json:"expires_at"`
}

type Review struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	ProductID int64          `json:"product_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt time.Time      `json:"created_at"`
}

type Seller struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	ShopName    sql.NullString `json:"shop_name"`
	ShopLogo    sql.NullString `json:"shop_logo"`
	Description sql.NullString `json:"description"`
	GstNumber   sql.NullString `json:"gst_number"`
	Status      SellerStatus   `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	Verified    bool           `json:"verified"`
}

type SellerDocument struct {
	ID          int64        `json:"id"`
	Document    DocumentType `json:"document"`
	DocumentUrl string       `json:"document_url"`
	SellerID    int64        `json:"seller_id"`
	UploadedAt  time.Time    `json:"uploaded_at"`
}

type User struct {
	ID        int64         `json:"id"`
	Email     string        `json:"email"`
	Username  string        `json:"username"`
	CreatedAt time.Time     `json:"created_at"`
	Role      Role          `json:"role"`
	AddressID sql.NullInt64 `json:"address_id"`
	Verified  bool          `json:"verified"`
	IsDeleted bool          `json:"is_deleted"`
	IsBanned  bool          `json:"is_banned"`
}

type UserView struct {
	ID        int64         `json:"id"`
	Email     string        `json:"email"`
	Username  string        `json:"username"`
	CreatedAt time.Time     `json:"created_at"`
	Role      Role          `json:"role"`
	AddressID sql.NullInt64 `json:"address_id"`
	Verified  bool          `json:"verified"`
	IsDeleted bool          `json:"is_deleted"`
	IsBanned  bool          `json:"is_banned"`
}

type VariantAttribute struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Value     string `json:"value"`
	VariantID int64  `json:"variant_id"`
}

type VariantImage struct {
	ID        int64  `json:"id"`
	ImageUrl  string `json:"image_url"`
	Position  int32  `json:"position"`
	VariantID int64  `json:"variant_id"`
}
