// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package db

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, address_id, total_amount)
VALUES ($1, $2, $3)
RETURNING id, user_id, address_id, total_amount, created_at, status, payment_status
`

type CreateOrderParams struct {
	UserID      int64         `json:"user_id"`
	AddressID   sql.NullInt64 `json:"address_id"`
	TotalAmount float64       `json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.UserID, arg.AddressID, arg.TotalAmount)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AddressID,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.Status,
		&i.PaymentStatus,
	)
	return i, err
}

const createOrderProduct = `-- name: CreateOrderProduct :one
INSERT INTO order_product (order_id, product_id, variant_id, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, variant_id, amount, order_id
`

type CreateOrderProductParams struct {
	OrderID   sql.NullInt64 `json:"order_id"`
	ProductID int64         `json:"product_id"`
	VariantID int64         `json:"variant_id"`
	Amount    int32         `json:"amount"`
}

func (q *Queries) CreateOrderProduct(ctx context.Context, arg CreateOrderProductParams) (OrderProduct, error) {
	row := q.db.QueryRowContext(ctx, createOrderProduct,
		arg.OrderID,
		arg.ProductID,
		arg.VariantID,
		arg.Amount,
	)
	var i OrderProduct
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.Amount,
		&i.OrderID,
	)
	return i, err
}

const decrementProductVariantStock = `-- name: DecrementProductVariantStock :exec
UPDATE product_variant
SET stock = stock - $2
WHERE id = $1 AND stock >= $2
`

type DecrementProductVariantStockParams struct {
	ID    int64 `json:"id"`
	Stock int32 `json:"stock"`
}

func (q *Queries) DecrementProductVariantStock(ctx context.Context, arg DecrementProductVariantStockParams) error {
	_, err := q.db.ExecContext(ctx, decrementProductVariantStock, arg.ID, arg.Stock)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, address_id, total_amount, created_at, status, payment_status FROM orders
WHERE id = $1 AND user_id = $2
`

type GetOrderByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AddressID,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.Status,
		&i.PaymentStatus,
	)
	return i, err
}
