// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"
	"database/sql"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM product
WHERE ($1::text IS NULL OR category_id = $1)
  AND ($2::bigint IS NULL OR seller_id = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
`

type CountProductsParams struct {
	CategoryID sql.NullString `json:"category_id"`
	SellerID   sql.NullInt64  `json:"seller_id"`
	IsActive   sql.NullBool   `json:"is_active"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts, arg.CategoryID, arg.SellerID, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (title, description, category_id, seller_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, is_active, seller_id, created_at, category_id
`

type CreateProductParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CategoryID  int64  `json:"category_id"`
	SellerID    int64  `json:"seller_id"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.SellerID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.SellerID,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variant (product_id, title, description, size, price, discounted, stock)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, size, description, discounted, title, price, stock, product_id
`

type CreateProductVariantParams struct {
	ProductID   int64         `json:"product_id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Size        string        `json:"size"`
	Price       float64       `json:"price"`
	Discounted  sql.NullInt32 `json:"discounted"`
	Stock       int32         `json:"stock"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, createProductVariant,
		arg.ProductID,
		arg.Title,
		arg.Description,
		arg.Size,
		arg.Price,
		arg.Discounted,
		arg.Stock,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.Size,
		&i.Description,
		&i.Discounted,
		&i.Title,
		&i.Price,
		&i.Stock,
		&i.ProductID,
	)
	return i, err
}

const createVariantAttribute = `-- name: CreateVariantAttribute :one
INSERT INTO variant_attribute (variant_id, name, value)
VALUES ($1, $2, $3)
RETURNING id, name, value, variant_id
`

type CreateVariantAttributeParams struct {
	VariantID int64  `json:"variant_id"`
	Name      string `json:"name"`
	Value     string `json:"value"`
}

func (q *Queries) CreateVariantAttribute(ctx context.Context, arg CreateVariantAttributeParams) (VariantAttribute, error) {
	row := q.db.QueryRowContext(ctx, createVariantAttribute, arg.VariantID, arg.Name, arg.Value)
	var i VariantAttribute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.VariantID,
	)
	return i, err
}

const createVariantImage = `-- name: CreateVariantImage :one
INSERT INTO variant_images (variant_id, image_key, position)
VALUES ($1, $2, $3)
RETURNING id, image_key, position, variant_id
`

type CreateVariantImageParams struct {
	VariantID int64  `json:"variant_id"`
	ImageKey  string `json:"image_key"`
	Position  int32  `json:"position"`
}

func (q *Queries) CreateVariantImage(ctx context.Context, arg CreateVariantImageParams) (VariantImage, error) {
	row := q.db.QueryRowContext(ctx, createVariantImage, arg.VariantID, arg.ImageKey, arg.Position)
	var i VariantImage
	err := row.Scan(
		&i.ID,
		&i.ImageKey,
		&i.Position,
		&i.VariantID,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE product
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT id, title, description, is_active, seller_id, created_at, category_id FROM product
WHERE ($1::text IS NULL OR category_id = $1)
  AND ($2::bigint IS NULL OR seller_id = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type GetAllProductsParams struct {
	CategoryID  sql.NullString `json:"category_id"`
	SellerID    sql.NullInt64  `json:"seller_id"`
	IsActive    sql.NullBool   `json:"is_active"`
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
}

func (q *Queries) GetAllProducts(ctx context.Context, arg GetAllProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts,
		arg.CategoryID,
		arg.SellerID,
		arg.IsActive,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.SellerID,
			&i.CreatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, title, description, is_active, seller_id, created_at, category_id FROM product
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.SellerID,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const getProductVariant = `-- name: GetProductVariant :one
SELECT id, size, description, discounted, title, price, stock, product_id FROM product_variant
WHERE product_id = $1 and id = $2
`

type GetProductVariantParams struct {
	ProductID int64 `json:"product_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) GetProductVariant(ctx context.Context, arg GetProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariant, arg.ProductID, arg.ID)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.Size,
		&i.Description,
		&i.Discounted,
		&i.Title,
		&i.Price,
		&i.Stock,
		&i.ProductID,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE product
SET title = $2,
    description = $3,
    category_id = $4,
    is_active = $5
WHERE id = $1
RETURNING id, title, description, is_active, seller_id, created_at, category_id
`

type UpdateProductParams struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	CategoryID  int64  `json:"category_id"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.SellerID,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE product_variant
SET title = $2,
    description = $3,
    size = $4,
    price = $5,
    discounted = $6,
    stock = $7
WHERE id = $1
RETURNING id, size, description, discounted, title, price, stock, product_id
`

type UpdateProductVariantParams struct {
	ID          int64         `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Size        string        `json:"size"`
	Price       float64       `json:"price"`
	Discounted  sql.NullInt32 `json:"discounted"`
	Stock       int32         `json:"stock"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, updateProductVariant,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Size,
		arg.Price,
		arg.Discounted,
		arg.Stock,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.Size,
		&i.Description,
		&i.Discounted,
		&i.Title,
		&i.Price,
		&i.Stock,
		&i.ProductID,
	)
	return i, err
}

const updateVariantAttribute = `-- name: UpdateVariantAttribute :one
UPDATE variant_attribute
SET name = $2,
    value = $3
WHERE id = $1
RETURNING id, name, value, variant_id
`

type UpdateVariantAttributeParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Value string `json:"value"`
}

func (q *Queries) UpdateVariantAttribute(ctx context.Context, arg UpdateVariantAttributeParams) (VariantAttribute, error) {
	row := q.db.QueryRowContext(ctx, updateVariantAttribute, arg.ID, arg.Name, arg.Value)
	var i VariantAttribute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.VariantID,
	)
	return i, err
}

const updateVariantImage = `-- name: UpdateVariantImage :one
UPDATE variant_images
SET image_key = $2,
    position = $3
WHERE id = $1
RETURNING id, image_key, position, variant_id
`

type UpdateVariantImageParams struct {
	ID       int64  `json:"id"`
	ImageKey string `json:"image_key"`
	Position int32  `json:"position"`
}

func (q *Queries) UpdateVariantImage(ctx context.Context, arg UpdateVariantImageParams) (VariantImage, error) {
	row := q.db.QueryRowContext(ctx, updateVariantImage, arg.ID, arg.ImageKey, arg.Position)
	var i VariantImage
	err := row.Scan(
		&i.ID,
		&i.ImageKey,
		&i.Position,
		&i.VariantID,
	)
	return i, err
}
