// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const addToCart = `-- name: AddToCart :exec
INSERT INTO cart (user_id, product_id, amount)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, product_id)
DO UPDATE SET amount = cart.amount + excluded.amount
`

type AddToCartParams struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
	Amount    int32 `json:"amount"`
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) error {
	_, err := q.db.ExecContext(ctx, addToCart, arg.UserID, arg.ProductID, arg.Amount)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (email, role)
VALUES ($1, $2)
RETURNING id
`

type CreateUserParams struct {
	Email string `json:"email"`
	Role  Role   `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Role)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserCredentials = `-- name: CreateUserCredentials :exec
INSERT INTO user_credentials (password, first_name, last_name, phone_number, user_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserCredentialsParams struct {
	Password    string         `json:"password"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	PhoneNumber sql.NullString `json:"phone_number"`
	UserID      int64          `json:"user_id"`
}

func (q *Queries) CreateUserCredentials(ctx context.Context, arg CreateUserCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, createUserCredentials,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.UserID,
	)
	return err
}

const getCart = `-- name: GetCart :many
SELECT c.id AS cart_id, c.amount, p.id AS product_id, p.title, p.price, p.discounted,
       p.image_url, s.shop_name
FROM cart c
JOIN product p ON p.id = c.product_id
JOIN seller s ON s.id = p.seller_id
WHERE c.user_id = $1
`

type GetCartRow struct {
	CartID     int64          `json:"cart_id"`
	Amount     int32          `json:"amount"`
	ProductID  int64          `json:"product_id"`
	Title      string         `json:"title"`
	Price      float64        `json:"price"`
	Discounted sql.NullInt32  `json:"discounted"`
	ImageUrl   string         `json:"image_url"`
	ShopName   sql.NullString `json:"shop_name"`
}

func (q *Queries) GetCart(ctx context.Context, userID int64) ([]GetCartRow, error) {
	rows, err := q.db.QueryContext(ctx, getCart, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartRow
	for rows.Next() {
		var i GetCartRow
		if err := rows.Scan(
			&i.CartID,
			&i.Amount,
			&i.ProductID,
			&i.Title,
			&i.Price,
			&i.Discounted,
			&i.ImageUrl,
			&i.ShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT u.id, u.email, u.role, u.verified, u.is_banned, c.password
FROM "user" u
JOIN user_credentials c ON c.user_id = u.id
WHERE u.email = $1
LIMIT 1
`

type GetUserForLoginRow struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	Role     Role   `json:"role"`
	Verified bool   `json:"verified"`
	IsBanned bool   `json:"is_banned"`
	Password string `json:"password"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Verified,
		&i.IsBanned,
		&i.Password,
	)
	return i, err
}

const removeFromCart = `-- name: RemoveFromCart :exec
DELETE FROM cart WHERE user_id = $1 AND product_id = $2
`

type RemoveFromCartParams struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) RemoveFromCart(ctx context.Context, arg RemoveFromCartParams) error {
	_, err := q.db.ExecContext(ctx, removeFromCart, arg.UserID, arg.ProductID)
	return err
}

const updateCart = `-- name: UpdateCart :exec
UPDATE cart
SET amount = $3
WHERE user_id = $1
AND product_id = $2
`

type UpdateCartParams struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
	Amount    int32 `json:"amount"`
}

func (q *Queries) UpdateCart(ctx context.Context, arg UpdateCartParams) error {
	_, err := q.db.ExecContext(ctx, updateCart, arg.UserID, arg.ProductID, arg.Amount)
	return err
}
