// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM product
WHERE ($1::text IS NULL OR category_id = $1)
  AND ($2::bigint IS NULL OR seller_id = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
`

type CountProductsParams struct {
	CategoryID sql.NullString `json:"category_id"`
	SellerID   sql.NullInt64  `json:"seller_id"`
	IsActive   sql.NullBool   `json:"is_active"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts, arg.CategoryID, arg.SellerID, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO account (account_id, provider, password, user_id)
VALUES ($1, $2, $3, $4)
`

type CreateAccountParams struct {
	AccountID string         `json:"account_id"`
	Provider  Provider       `json:"provider"`
	Password  sql.NullString `json:"password"`
	UserID    int64          `json:"user_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.AccountID,
		arg.Provider,
		arg.Password,
		arg.UserID,
	)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (title, description, category_id, seller_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, is_active, seller_id, created_at, category_id
`

type CreateProductParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CategoryID  int64  `json:"category_id"`
	SellerID    int64  `json:"seller_id"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.SellerID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.SellerID,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variant (product_id, title, description, size, price, discounted, stock)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, size, description, discounted, title, price, stock, product_id
`

type CreateProductVariantParams struct {
	ProductID   int64         `json:"product_id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Size        string        `json:"size"`
	Price       float64       `json:"price"`
	Discounted  sql.NullInt32 `json:"discounted"`
	Stock       int32         `json:"stock"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, createProductVariant,
		arg.ProductID,
		arg.Title,
		arg.Description,
		arg.Size,
		arg.Price,
		arg.Discounted,
		arg.Stock,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.Size,
		&i.Description,
		&i.Discounted,
		&i.Title,
		&i.Price,
		&i.Stock,
		&i.ProductID,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_token (id,token, user_id, ip_address, expires_at)
VALUES ($1, $2, $3, $4,$5)
`

type CreateRefreshTokenParams struct {
	ID        string         `json:"id"`
	Token     string         `json:"token"`
	UserID    int64          `json:"user_id"`
	IpAddress sql.NullString `json:"ip_address"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const createRequestFileUpload = `-- name: CreateRequestFileUpload :one
INSERT INTO uploads (key, filename, content_type, file_size, upload_type, expires_at, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, filename, key, content_type, file_size, upload_type, status, user_id, uploaded_at, expires_at
`

type CreateRequestFileUploadParams struct {
	Key         string    `json:"key"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	FileSize    int64     `json:"file_size"`
	UploadType  string    `json:"upload_type"`
	ExpiresAt   time.Time `json:"expires_at"`
	UserID      int64     `json:"user_id"`
}

func (q *Queries) CreateRequestFileUpload(ctx context.Context, arg CreateRequestFileUploadParams) (Upload, error) {
	row := q.db.QueryRowContext(ctx, createRequestFileUpload,
		arg.Key,
		arg.Filename,
		arg.ContentType,
		arg.FileSize,
		arg.UploadType,
		arg.ExpiresAt,
		arg.UserID,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Key,
		&i.ContentType,
		&i.FileSize,
		&i.UploadType,
		&i.Status,
		&i.UserID,
		&i.UploadedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (email, role, username)
VALUES ($1, $2, $3) 
RETURNING id, email, role
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Role     Role   `json:"role"`
	Username string `json:"username"`
}

type CreateUserRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
	Role  Role   `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Role, arg.Username)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Role)
	return i, err
}

const createVariantAttribute = `-- name: CreateVariantAttribute :one
INSERT INTO variant_attribute (variant_id, name, value)
VALUES ($1, $2, $3)
RETURNING id, name, value, variant_id
`

type CreateVariantAttributeParams struct {
	VariantID int64  `json:"variant_id"`
	Name      string `json:"name"`
	Value     string `json:"value"`
}

func (q *Queries) CreateVariantAttribute(ctx context.Context, arg CreateVariantAttributeParams) (VariantAttribute, error) {
	row := q.db.QueryRowContext(ctx, createVariantAttribute, arg.VariantID, arg.Name, arg.Value)
	var i VariantAttribute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.VariantID,
	)
	return i, err
}

const createVariantImage = `-- name: CreateVariantImage :one
INSERT INTO variant_images (variant_id, image_key, position)
VALUES ($1, $2, $3)
RETURNING id, image_key, position, variant_id
`

type CreateVariantImageParams struct {
	VariantID int64  `json:"variant_id"`
	ImageKey  string `json:"image_key"`
	Position  int32  `json:"position"`
}

func (q *Queries) CreateVariantImage(ctx context.Context, arg CreateVariantImageParams) (VariantImage, error) {
	row := q.db.QueryRowContext(ctx, createVariantImage, arg.VariantID, arg.ImageKey, arg.Position)
	var i VariantImage
	err := row.Scan(
		&i.ID,
		&i.ImageKey,
		&i.Position,
		&i.VariantID,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE product
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const deleteRefreshTokensByID = `-- name: DeleteRefreshTokensByID :exec
DELETE FROM refresh_token
WHERE id = $1
`

func (q *Queries) DeleteRefreshTokensByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensByID, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE "user"
SET is_deleted = TRUE
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many

SELECT id, title, description, is_active, seller_id, created_at, category_id FROM product
WHERE ($1::text IS NULL OR category_id = $1)
  AND ($2::bigint IS NULL OR seller_id = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type GetAllProductsParams struct {
	CategoryID  sql.NullString `json:"category_id"`
	SellerID    sql.NullInt64  `json:"seller_id"`
	IsActive    sql.NullBool   `json:"is_active"`
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
}

// Product Queries
func (q *Queries) GetAllProducts(ctx context.Context, arg GetAllProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts,
		arg.CategoryID,
		arg.SellerID,
		arg.IsActive,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.SellerID,
			&i.CreatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderHistory = `-- name: GetOrderHistory :many
SELECT id, user_id, address, seller_id, address_id, total_amount, created_at, status, payment_status FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrderHistory(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrderHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.SellerID,
			&i.AddressID,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.Status,
			&i.PaymentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, title, description, is_active, seller_id, created_at, category_id FROM product
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.SellerID,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const getProductBySeller = `-- name: GetProductBySeller :one
SELECT id, title, description, is_active, seller_id, created_at, category_id FROM product
WHERE id = $1 AND seller_id = $2
`

type GetProductBySellerParams struct {
	ID       int64 `json:"id"`
	SellerID int64 `json:"seller_id"`
}

func (q *Queries) GetProductBySeller(ctx context.Context, arg GetProductBySellerParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySeller, arg.ID, arg.SellerID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.SellerID,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, token, user_id, revoked, ip_address, created_at, expires_at
FROM refresh_token
WHERE id = $1
`

type GetRefreshTokenRow struct {
	ID        string         `json:"id"`
	Token     string         `json:"token"`
	UserID    int64          `json:"user_id"`
	Revoked   bool           `json:"revoked"`
	IpAddress sql.NullString `json:"ip_address"`
	CreatedAt time.Time      `json:"created_at"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, id string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, id)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.Revoked,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSellerByUserID = `-- name: GetSellerByUserID :one
SELECT id, user_id, shop_name, shop_logo, description, gst_number, status, created_at, verified FROM seller
WHERE user_id = $1
`

func (q *Queries) GetSellerByUserID(ctx context.Context, userID int64) (Seller, error) {
	row := q.db.QueryRowContext(ctx, getSellerByUserID, userID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopName,
		&i.ShopLogo,
		&i.Description,
		&i.GstNumber,
		&i.Status,
		&i.CreatedAt,
		&i.Verified,
	)
	return i, err
}

const getUploadRequestByKey = `-- name: GetUploadRequestByKey :one
SELECT id, filename, key, content_type, file_size, upload_type, status, user_id, uploaded_at, expires_at FROM uploads
WHERE key = $1
`

func (q *Queries) GetUploadRequestByKey(ctx context.Context, key string) (Upload, error) {
	row := q.db.QueryRowContext(ctx, getUploadRequestByKey, key)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Key,
		&i.ContentType,
		&i.FileSize,
		&i.UploadType,
		&i.Status,
		&i.UserID,
		&i.UploadedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserAddresses = `-- name: GetUserAddresses :many
SELECT id, name, pincode, area, city, state, country, phone_number, user_id, last_used FROM address
WHERE user_id = $1
`

func (q *Queries) GetUserAddresses(ctx context.Context, userID int64) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, getUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Pincode,
			&i.Area,
			&i.City,
			&i.State,
			&i.Country,
			&i.PhoneNumber,
			&i.UserID,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByAccountID = `-- name: GetUserByAccountID :one
SELECT u.id, u.email, u.role, a.account_id, a.provider, a.password,u.username
FROM "user_view" u
JOIN account a ON u.id = a.user_id
WHERE a.account_id = $1
`

type GetUserByAccountIDRow struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	Role      Role           `json:"role"`
	AccountID string         `json:"account_id"`
	Provider  Provider       `json:"provider"`
	Password  sql.NullString `json:"password"`
	Username  string         `json:"username"`
}

func (q *Queries) GetUserByAccountID(ctx context.Context, accountID string) (GetUserByAccountIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByAccountID, accountID)
	var i GetUserByAccountIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.AccountID,
		&i.Provider,
		&i.Password,
		&i.Username,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, role, username
FROM "user_view"
WHERE id = $1
`

type GetUserByIDRow struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	Role     Role   `json:"role"`
	Username string `json:"username"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Username,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE product
SET title = $2,
    description = $3,
    category_id = $4,
    is_active = $5
WHERE id = $1
RETURNING id, title, description, is_active, seller_id, created_at, category_id
`

type UpdateProductParams struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	CategoryID  int64  `json:"category_id"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.SellerID,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE product_variant
SET title = $2,
    description = $3,
    size = $4,
    price = $5,
    discounted = $6,
    stock = $7
WHERE id = $1
RETURNING id, size, description, discounted, title, price, stock, product_id
`

type UpdateProductVariantParams struct {
	ID          int64         `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Size        string        `json:"size"`
	Price       float64       `json:"price"`
	Discounted  sql.NullInt32 `json:"discounted"`
	Stock       int32         `json:"stock"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, updateProductVariant,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Size,
		arg.Price,
		arg.Discounted,
		arg.Stock,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.Size,
		&i.Description,
		&i.Discounted,
		&i.Title,
		&i.Price,
		&i.Stock,
		&i.ProductID,
	)
	return i, err
}

const updateRefreshTokenRevoked = `-- name: UpdateRefreshTokenRevoked :exec
UPDATE refresh_token
SET revoked = $2 , last_used = $3
WHERE id = $1
`

type UpdateRefreshTokenRevokedParams struct {
	ID       string       `json:"id"`
	Revoked  bool         `json:"revoked"`
	LastUsed sql.NullTime `json:"last_used"`
}

func (q *Queries) UpdateRefreshTokenRevoked(ctx context.Context, arg UpdateRefreshTokenRevokedParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenRevoked, arg.ID, arg.Revoked, arg.LastUsed)
	return err
}

const updateUserAddress = `-- name: UpdateUserAddress :exec
UPDATE address
SET name = $2,
    pincode = $3,
    area = $4,
    city = $5,
    state = $6,
    country = $7,
    phone_number = $8
WHERE id = $1
`

type UpdateUserAddressParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Pincode     int32  `json:"pincode"`
	Area        string `json:"area"`
	City        string `json:"city"`
	State       string `json:"state"`
	Country     string `json:"country"`
	PhoneNumber int64  `json:"phone_number"`
}

func (q *Queries) UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAddress,
		arg.ID,
		arg.Name,
		arg.Pincode,
		arg.Area,
		arg.City,
		arg.State,
		arg.Country,
		arg.PhoneNumber,
	)
	return err
}

const updateVariantAttribute = `-- name: UpdateVariantAttribute :one
UPDATE variant_attribute
SET name = $2,
    value = $3
WHERE id = $1
RETURNING id, name, value, variant_id
`

type UpdateVariantAttributeParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Value string `json:"value"`
}

func (q *Queries) UpdateVariantAttribute(ctx context.Context, arg UpdateVariantAttributeParams) (VariantAttribute, error) {
	row := q.db.QueryRowContext(ctx, updateVariantAttribute, arg.ID, arg.Name, arg.Value)
	var i VariantAttribute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.VariantID,
	)
	return i, err
}

const updateVariantImage = `-- name: UpdateVariantImage :one
UPDATE variant_images
SET image_key = $2,
    position = $3
WHERE id = $1
RETURNING id, image_key, position, variant_id
`

type UpdateVariantImageParams struct {
	ID       int64  `json:"id"`
	ImageKey string `json:"image_key"`
	Position int32  `json:"position"`
}

func (q *Queries) UpdateVariantImage(ctx context.Context, arg UpdateVariantImageParams) (VariantImage, error) {
	row := q.db.QueryRowContext(ctx, updateVariantImage, arg.ID, arg.ImageKey, arg.Position)
	var i VariantImage
	err := row.Scan(
		&i.ID,
		&i.ImageKey,
		&i.Position,
		&i.VariantID,
	)
	return i, err
}
