// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddToCart(ctx context.Context, arg AddToCartParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	CreateUserCredentials(ctx context.Context, arg CreateUserCredentialsParams) error
	GetCart(ctx context.Context, userID int64) ([]GetCartRow, error)
	GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error)
	RemoveFromCart(ctx context.Context, arg RemoveFromCartParams) error
	UpdateCart(ctx context.Context, arg UpdateCartParams) error
}

var _ Querier = (*Queries)(nil)
