// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateBuyer(ctx context.Context, userID int64) (Buyer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderProduct(ctx context.Context, arg CreateOrderProductParams) (OrderProduct, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateRequestFileUpload(ctx context.Context, arg CreateRequestFileUploadParams) (Upload, error)
	CreateSeller(ctx context.Context, userID int64) (Seller, error)
	CreateSellerDocument(ctx context.Context, arg CreateSellerDocumentParams) (SellerDocument, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateVariantAttribute(ctx context.Context, arg CreateVariantAttributeParams) (VariantAttribute, error)
	CreateVariantImage(ctx context.Context, arg CreateVariantImageParams) (VariantImage, error)
	DecrementProductVariantStock(ctx context.Context, arg DecrementProductVariantStockParams) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteRefreshTokensByID(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id int64) error
	GetAllProducts(ctx context.Context, arg GetAllProductsParams) ([]Product, error)
	GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error)
	GetOrderHistory(ctx context.Context, userID int64) ([]Order, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
	GetProductBySeller(ctx context.Context, arg GetProductBySellerParams) (Product, error)
	GetProductVariant(ctx context.Context, arg GetProductVariantParams) (ProductVariant, error)
	GetRefreshToken(ctx context.Context, id string) (GetRefreshTokenRow, error)
	GetSellerByUserID(ctx context.Context, userID int64) (Seller, error)
	GetUploadRequestByKey(ctx context.Context, key string) (Upload, error)
	GetUserAddresses(ctx context.Context, userID int64) ([]Address, error)
	GetUserByAccountID(ctx context.Context, accountID string) (GetUserByAccountIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (UserView, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error)
	UpdateRefreshTokenRevoked(ctx context.Context, arg UpdateRefreshTokenRevokedParams) error
	UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) error
	UpdateVariantAttribute(ctx context.Context, arg UpdateVariantAttributeParams) (VariantAttribute, error)
	UpdateVariantImage(ctx context.Context, arg UpdateVariantImageParams) (VariantImage, error)
	UpsertSellerCredentials(ctx context.Context, arg UpsertSellerCredentialsParams) (SellerCredential, error)
}

var _ Querier = (*Queries)(nil)
