// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetCart(ctx context.Context, userID int64) ([]GetCartRow, error)
	RemoveFromCart(ctx context.Context, arg RemoveFromCartParams) error
	UpdateCart(ctx context.Context, arg UpdateCartParams) error
}

var _ Querier = (*Queries)(nil)
