// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO account (account_id, provider, password, user_id)
VALUES ($1, $2, $3, $4)
`

type CreateAccountParams struct {
	AccountID string         `json:"account_id"`
	Provider  Provider       `json:"provider"`
	Password  sql.NullString `json:"password"`
	UserID    int64          `json:"user_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.AccountID,
		arg.Provider,
		arg.Password,
		arg.UserID,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_token (id,token, user_id, ip_address, expires_at)
VALUES ($1, $2, $3, $4,$5)
`

type CreateRefreshTokenParams struct {
	ID        string         `json:"id"`
	Token     string         `json:"token"`
	UserID    int64          `json:"user_id"`
	IpAddress sql.NullString `json:"ip_address"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (email, role)
VALUES ($1, $2) 
RETURNING id, email, role
`

type CreateUserParams struct {
	Email string `json:"email"`
	Role  Role   `json:"role"`
}

type CreateUserRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
	Role  Role   `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Role)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Role)
	return i, err
}

const deleteRefreshTokensByID = `-- name: DeleteRefreshTokensByID :exec
DELETE FROM refresh_token
WHERE id = $1
`

func (q *Queries) DeleteRefreshTokensByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensByID, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE "user"
SET is_deleted = TRUE
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getOrderHistory = `-- name: GetOrderHistory :many
SELECT id, user_id, address, seller_id, address_id, total_amount, created_at, status, payment_status FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrderHistory(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrderHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.SellerID,
			&i.AddressID,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.Status,
			&i.PaymentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, token, user_id, revoked, ip_address, created_at, expires_at
FROM refresh_token
WHERE id = $1
`

type GetRefreshTokenRow struct {
	ID        string         `json:"id"`
	Token     string         `json:"token"`
	UserID    int64          `json:"user_id"`
	Revoked   bool           `json:"revoked"`
	IpAddress sql.NullString `json:"ip_address"`
	CreatedAt time.Time      `json:"created_at"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, id string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, id)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.Revoked,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserAddresses = `-- name: GetUserAddresses :many
SELECT id, name, pincode, area, city, state, country, phone_number, user_id, last_used FROM address
WHERE user_id = $1
`

func (q *Queries) GetUserAddresses(ctx context.Context, userID int64) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, getUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Pincode,
			&i.Area,
			&i.City,
			&i.State,
			&i.Country,
			&i.PhoneNumber,
			&i.UserID,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByAccountID = `-- name: GetUserByAccountID :one
SELECT u.id, u.email, u.role, a.account_id, a.provider, a.password,u.username
FROM "user_view" u
JOIN account a ON u.id = a.user_id
WHERE a.account_id = $1
`

type GetUserByAccountIDRow struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	Role      Role           `json:"role"`
	AccountID string         `json:"account_id"`
	Provider  Provider       `json:"provider"`
	Password  sql.NullString `json:"password"`
	Username  string         `json:"username"`
}

func (q *Queries) GetUserByAccountID(ctx context.Context, accountID string) (GetUserByAccountIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByAccountID, accountID)
	var i GetUserByAccountIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.AccountID,
		&i.Provider,
		&i.Password,
		&i.Username,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, role, username
FROM "user_view"
WHERE id = $1
`

type GetUserByIDRow struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	Role     Role   `json:"role"`
	Username string `json:"username"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Username,
	)
	return i, err
}

const updateRefreshTokenRevoked = `-- name: UpdateRefreshTokenRevoked :exec
UPDATE refresh_token
SET revoked = $2 , last_used = $3
WHERE id = $1
`

type UpdateRefreshTokenRevokedParams struct {
	ID       string       `json:"id"`
	Revoked  bool         `json:"revoked"`
	LastUsed sql.NullTime `json:"last_used"`
}

func (q *Queries) UpdateRefreshTokenRevoked(ctx context.Context, arg UpdateRefreshTokenRevokedParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenRevoked, arg.ID, arg.Revoked, arg.LastUsed)
	return err
}

const updateUserAddress = `-- name: UpdateUserAddress :exec
UPDATE address
SET name = $2,
    pincode = $3,
    area = $4,
    city = $5,
    state = $6,
    country = $7,
    phone_number = $8
WHERE id = $1
`

type UpdateUserAddressParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Pincode     int32  `json:"pincode"`
	Area        string `json:"area"`
	City        string `json:"city"`
	State       string `json:"state"`
	Country     string `json:"country"`
	PhoneNumber int64  `json:"phone_number"`
}

func (q *Queries) UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAddress,
		arg.ID,
		arg.Name,
		arg.Pincode,
		arg.Area,
		arg.City,
		arg.State,
		arg.Country,
		arg.PhoneNumber,
	)
	return err
}
