// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uploads.sql

package db

import (
	"context"
	"time"
)

const createRequestFileUpload = `-- name: CreateRequestFileUpload :one
INSERT INTO uploads (key, filename, content_type, file_size, upload_type, expires_at, user_id)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, filename, key, content_type, file_size, upload_type, status, user_id, uploaded_at, expires_at
`

type CreateRequestFileUploadParams struct {
	Key         string    `json:"key"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	FileSize    int64     `json:"file_size"`
	UploadType  string    `json:"upload_type"`
	ExpiresAt   time.Time `json:"expires_at"`
	UserID      int64     `json:"user_id"`
}

func (q *Queries) CreateRequestFileUpload(ctx context.Context, arg CreateRequestFileUploadParams) (Upload, error) {
	row := q.db.QueryRowContext(ctx, createRequestFileUpload,
		arg.Key,
		arg.Filename,
		arg.ContentType,
		arg.FileSize,
		arg.UploadType,
		arg.ExpiresAt,
		arg.UserID,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Key,
		&i.ContentType,
		&i.FileSize,
		&i.UploadType,
		&i.Status,
		&i.UserID,
		&i.UploadedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUploadRequestByKey = `-- name: GetUploadRequestByKey :one
SELECT id, filename, key, content_type, file_size, upload_type, status, user_id, uploaded_at, expires_at FROM uploads WHERE key = $1
`

func (q *Queries) GetUploadRequestByKey(ctx context.Context, key string) (Upload, error) {
	row := q.db.QueryRowContext(ctx, getUploadRequestByKey, key)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Key,
		&i.ContentType,
		&i.FileSize,
		&i.UploadType,
		&i.Status,
		&i.UserID,
		&i.UploadedAt,
		&i.ExpiresAt,
	)
	return i, err
}
