// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (email, username)
VALUES ($1, $2)
RETURNING id, email
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

type CreateUserRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Username)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE "user"
SET is_deleted = TRUE
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getOrderHistory = `-- name: GetOrderHistory :many
SELECT id, user_id, address, seller_id, address_id, total_amount, created_at, status, payment_status FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrderHistory(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrderHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.SellerID,
			&i.AddressID,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.Status,
			&i.PaymentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAddresses = `-- name: GetUserAddresses :many
SELECT id, name, pincode, area, city, state, country, phone_number, user_id, last_used FROM address
WHERE user_id = $1
`

func (q *Queries) GetUserAddresses(ctx context.Context, userID int64) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, getUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Pincode,
			&i.Area,
			&i.City,
			&i.State,
			&i.Country,
			&i.PhoneNumber,
			&i.UserID,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByAccountID = `-- name: GetUserByAccountID :one
SELECT u.id, u.email, a.account_id, a.provider, a.password, u.username
FROM user_view u
JOIN account a ON u.id = a.user_id
WHERE a.account_id = $1
`

type GetUserByAccountIDRow struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	AccountID string         `json:"account_id"`
	Provider  Provider       `json:"provider"`
	Password  sql.NullString `json:"password"`
	Username  string         `json:"username"`
}

func (q *Queries) GetUserByAccountID(ctx context.Context, accountID string) (GetUserByAccountIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByAccountID, accountID)
	var i GetUserByAccountIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.AccountID,
		&i.Provider,
		&i.Password,
		&i.Username,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, created_at, address_id, verified, is_deleted, is_banned FROM user_view WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (UserView, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i UserView
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
		&i.AddressID,
		&i.Verified,
		&i.IsDeleted,
		&i.IsBanned,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email,  username
FROM user_view
WHERE id = $1
`

type GetUserByIDRow struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const updateUserAddress = `-- name: UpdateUserAddress :exec
UPDATE address
SET name = $2,
    pincode = $3,
    area = $4,
    city = $5,
    state = $6,
    country = $7,
    phone_number = $8
WHERE id = $1
`

type UpdateUserAddressParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Pincode     int32  `json:"pincode"`
	Area        string `json:"area"`
	City        string `json:"city"`
	State       string `json:"state"`
	Country     string `json:"country"`
	PhoneNumber int64  `json:"phone_number"`
}

func (q *Queries) UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAddress,
		arg.ID,
		arg.Name,
		arg.Pincode,
		arg.Area,
		arg.City,
		arg.State,
		arg.Country,
		arg.PhoneNumber,
	)
	return err
}
