CREATE TYPE seller_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

CREATE TYPE order_status AS ENUM (
  'PENDING',
  'PROCESSING',
  'SHIPPED',
  'DELIVERED',
  'CANCELLED'
);

CREATE TYPE payment_status AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED');

CREATE TYPE document_type AS ENUM (
  'GST_CERTIFICATE',
  'BUSINESS_LICENSE',
  'IDENTITY_PROOF'
);

CREATE TYPE provider AS ENUM ('GOOGLE', 'FACEBOOK', 'GITHUB', 'CREDENTIALS');

CREATE TYPE upload_status AS ENUM ('PENDING', 'COMPLETED', 'Expired')